"""Phase 5 feature 5: fail2ban integration. XHIGH effort per the goal --
same class of risk as the firewall feature (Feature 4): a wrong ban
action can lock out a legitimate operator, so jail bootstrap is
conservative and every parser here was built against this server's own
real `fail2ban-client`/log output, not assumed from documentation.

Jails managed: `sshd` (Ubuntu's fail2ban package already ships this
enabled by default via /etc/fail2ban/jail.d/defaults-debian.conf,
confirmed live -- nothing to add), plus four this feature adds via its
own `/etc/fail2ban/jail.d/forgehost.conf` drop-in: `postfix`/`dovecot`
(stock fail2ban filters that ship with the package but aren't enabled by
default), a custom `forgehost-panel-login` filter for this project's own
`/login` endpoint, and a custom `ols-scan` filter for OpenLiteSpeed
(no stock fail2ban filter targets LiteSpeed's access log format).
"""
from __future__ import annotations

import datetime as dt
import ipaddress
import os
import re
from pathlib import Path

from shared.validation import ValidationError

from daemon.procutil import run

JAIL_D_PATH = "/etc/fail2ban/jail.d/forgehost.conf"
FILTER_PANEL_LOGIN_PATH = "/etc/fail2ban/filter.d/forgehost-panel-login.conf"
FILTER_OLS_SCAN_PATH = "/etc/fail2ban/filter.d/ols-scan.conf"
FAIL2BAN_LOG_PATH = "/var/log/fail2ban.log"

MANAGED_JAILS = {"sshd", "postfix", "dovecot", "forgehost-panel-login", "ols-scan"}


def _atomic_write(path: str, content: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + f".tmp.{os.getpid()}")
    tmp.write_text(content)
    os.chmod(tmp, 0o644)
    tmp.rename(p)


_PANEL_LOGIN_FILTER = """# Managed by Forgehost (daemon/fail2ban.py).
# Matches forgehost-api's own uvicorn access-log line for a failed /login
# POST (401 = bad credentials, 429 = already locked out by the
# application-layer throttle, Security audit finding F2) -- confirmed
# against this server's real journal MESSAGE field
# (`journalctl -u forgehost-api -o cat`) before writing this regex, not
# assumed from uvicorn's documentation.
[Definition]
failregex = ^INFO:\\s+<HOST>:\\d+ - "POST /login HTTP/1\\.1" (401|429)
ignoreregex =
"""

_OLS_SCAN_FILTER = """# Managed by Forgehost (daemon/fail2ban.py).
# No stock fail2ban filter targets OpenLiteSpeed's access log (Combined
# Log Format, confirmed against this server's real
# /usr/local/lsws/logs/access.log). Bans IPs generating repeated 404s --
# real scanner traffic on this box (Censys, zgrab, and generic
# vulnerability probes for wp-login.php/.env/phpmyadmin-style paths) all
# show this exact signature.
[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD|PUT|DELETE) [^"]*" 404
ignoreregex =
"""

_JAIL_D_CONF = """# Managed by Forgehost (daemon/fail2ban.py). Do not edit by hand --
# regenerated by the "install/reconfigure jails" action in the admin UI.
#
# backend=systemd + journalmatch, not logpath, for every service-backed
# jail here -- matches this system's own already-working sshd jail
# convention (/etc/fail2ban/jail.d/defaults-debian.conf sets
# backend=systemd globally) rather than introducing a second, untested
# log-reading mechanism. postfix's journalmatch targets
# `postfix@-.service` specifically, not the decoy `postfix.service`
# wrapper unit (daemon/servicemgr.py's own CHECKPOINT documents the same
# real-unit-name finding for Feature 2's service manager).

[postfix]
enabled = true
backend = systemd
journalmatch = _SYSTEMD_UNIT=postfix@-.service

[dovecot]
enabled = true
backend = systemd
journalmatch = _SYSTEMD_UNIT=dovecot.service

[forgehost-panel-login]
enabled = true
filter = forgehost-panel-login
backend = systemd
journalmatch = _SYSTEMD_UNIT=forgehost-api.service
port = 9443
maxretry = 5
findtime = 300
bantime = 900

[ols-scan]
enabled = true
filter = ols-scan
backend = auto
logpath = /usr/local/lsws/logs/access.log
port = http,https
maxretry = 20
findtime = 60
bantime = 3600
"""


def bootstrap_jails(params: dict | None = None) -> dict:
    """Idempotent -- writes the filter/jail config, then reloads fail2ban
    so the new jails take effect immediately. Safe to call repeatedly
    (e.g. re-run after an operator tweaks then wants to reset to
    defaults)."""
    _atomic_write(FILTER_PANEL_LOGIN_PATH, _PANEL_LOGIN_FILTER)
    _atomic_write(FILTER_OLS_SCAN_PATH, _OLS_SCAN_FILTER)
    _atomic_write(JAIL_D_PATH, _JAIL_D_CONF)
    result = run(["fail2ban-client", "reload"], timeout=30)
    if not result.ok:
        raise RuntimeError(f"fail2ban-client reload failed: {result.stderr.strip() or result.stdout.strip()}")
    return {"status": "ok", "jails": sorted(MANAGED_JAILS)}


# --- status / listing -------------------------------------------------------

_INT_FIELD_RE = {
    "currently_failed": re.compile(r"Currently failed:\s*(\d+)"),
    "total_failed": re.compile(r"Total failed:\s*(\d+)"),
    "currently_banned": re.compile(r"Currently banned:\s*(\d+)"),
    "total_banned": re.compile(r"Total banned:\s*(\d+)"),
}
_BANNED_IP_LIST_RE = re.compile(r"Banned IP list:\s*(.*)")


def _list_jail_names() -> list[str]:
    result = run(["fail2ban-client", "status"], timeout=15)
    for line in result.stdout.splitlines():
        if "Jail list:" in line:
            raw = line.split("Jail list:", 1)[1].strip()
            return [j.strip() for j in raw.split(",") if j.strip()]
    return []


def _jail_status(jail: str) -> dict:
    result = run(["fail2ban-client", "status", jail], timeout=15)
    data = {"jail": jail, "currently_failed": 0, "total_failed": 0, "currently_banned": 0, "total_banned": 0, "banned_ips": []}
    if not result.ok:
        data["error"] = result.stderr.strip() or result.stdout.strip()
        return data
    for line in result.stdout.splitlines():
        for key, pattern in _INT_FIELD_RE.items():
            m = pattern.search(line)
            if m:
                data[key] = int(m.group(1))
        m = _BANNED_IP_LIST_RE.search(line)
        if m:
            data["banned_ips"] = [ip for ip in m.group(1).split() if ip]
    return data


def list_jails(params: dict) -> dict:
    jails = [_jail_status(name) for name in _list_jail_names()]
    return {"jails": jails}


def get_jail(params: dict) -> dict:
    jail = params["jail"]
    if jail not in _list_jail_names():
        raise ValidationError(f"jail '{jail}' is not currently active")
    return _jail_status(jail)


def _validate_jail(jail: str) -> str:
    active = _list_jail_names()
    if jail not in active:
        raise ValidationError(f"jail '{jail}' is not currently active (active: {active})")
    return jail


def _validate_ip(ip: str) -> str:
    try:
        ipaddress.ip_address(ip)
    except ValueError:
        raise ValidationError(f"'{ip}' is not a valid IP address") from None
    return ip


def unban_ip(params: dict) -> dict:
    jail = _validate_jail(params["jail"])
    ip = _validate_ip(params["ip"])
    result = run(["fail2ban-client", "set", jail, "unbanip", ip], timeout=15)
    if not result.ok:
        raise RuntimeError(f"unban failed: {result.stderr.strip() or result.stdout.strip()}")
    return {"jail": jail, "ip": ip, "status": "unbanned"}


def unban_all_in_jail(params: dict) -> dict:
    jail = _validate_jail(params["jail"])
    status = _jail_status(jail)
    unbanned = []
    for ip in status["banned_ips"]:
        result = run(["fail2ban-client", "set", jail, "unbanip", ip], timeout=15)
        if result.ok:
            unbanned.append(ip)
    return {"jail": jail, "unbanned": unbanned, "count": len(unbanned)}


# --- recent ban events, parsed from fail2ban's own log ----------------------

_EVENT_RE = re.compile(
    r"\A(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),\d+\s+fail2ban\.actions\s+\[\d+\]:\s+NOTICE\s+\[(?P<jail>\S+)\]\s+(?P<action>Ban|Unban)\s+(?P<ip>\S+)"
)


def recent_events(params: dict) -> dict:
    limit = int(params.get("limit", 50) or 50)
    jail_filter = params.get("jail")
    result = run(["tail", "-n", "2000", FAIL2BAN_LOG_PATH], timeout=15)
    events = []
    for line in result.stdout.splitlines():
        m = _EVENT_RE.match(line)
        if not m:
            continue
        if jail_filter and m.group("jail") != jail_filter:
            continue
        events.append(
            {
                "timestamp": m.group("ts"),
                "jail": m.group("jail"),
                "action": m.group("action"),
                "ip": m.group("ip"),
            }
        )
    events.reverse()  # most recent first
    return {"events": events[:limit]}
