"""Postfix/Dovecot virtual mailbox provisioning (Phase e).

RESEARCH.md SS6 / ARCHITECTURE.md SS4: Postfix's `proxy:mysql:` maps and
Dovecot's SQL passdb/userdb query forgehost_mail live -- routine mailbox/
domain CRUD here needs **no Postfix/Dovecot reload at all**, just an INSERT/
UPDATE/DELETE against forgehost_mail (a real operational difference from
Phase b/e's vhost/MariaDB config, confirmed by this build's real testing
below). The static structural config (lookup map files, dovecot-sql.conf.ext,
LMTP/auth sockets) was hand-applied once during Phase e setup, documented in
CHECKPOINT-e.md -- it doesn't change per mailbox and so isn't regenerated by
this module.

forgehost_daemon (the same admin user from Phase d) is used for writes here;
forgehost_mailro (SELECT-only) is the credential embedded in Postfix's and
Dovecot's own config files, per RESEARCH.md SS6.
"""
from __future__ import annotations

import os
import pwd

import pymysql

from shared.config import settings
from shared.validation import ValidationError, validate_domain, validate_mailbox_local_part

from daemon.procutil import run

# A low *system* uid/gid (SYS_UID_MAX on this distro is 999), matching
# convention for service accounts (mysql/postfix/dovecot are all in this
# range too) -- deliberately NOT a high number like 30000, which was tried
# first and immediately caused a real bug: useradd allocates the *next*
# regular-account uid starting from the highest existing uid, not the
# lowest free gap, so every hosting account created afterward got uid
# 30001, 30002, ... instead of continuing from 1000. Caught by real testing
# (an account's own uid showed up as 30001 right after vmail was created at
# 30000), fixed by moving vmail into the system range where it belongs.
VMAIL_UID = 150
VMAIL_GID = 150
VMAIL_BASE = "/var/vmail"


def _connect():
    return pymysql.connect(
        unix_socket=settings.mariadb_socket,
        user=settings.mariadb_admin_user,
        password=settings.mariadb_admin_password,
        database="forgehost_mail",
        autocommit=True,
        cursorclass=pymysql.cursors.DictCursor,
    )


def hash_password(password: str) -> str:
    """doveadm pw, not a hand-rolled crypt() call -- guarantees Dovecot-
    compatible output by construction (RESEARCH.md SS6, the HestiaCP
    pattern over ISPConfig's reimplemented PHP crypt())."""
    result = run(["doveadm", "pw", "-s", "ARGON2ID", "-p", password], timeout=15, check=True)
    return result.stdout.strip()


def domain_exists(domain: str) -> bool:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT id FROM mail_domain WHERE domain = %s", (domain,))
            return cur.fetchone() is not None
    finally:
        conn.close()


def create_mail_domain(domain: str) -> int:
    validate_domain(domain)
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute("INSERT INTO mail_domain (domain, active) VALUES (%s, 1)", (domain,))
            domain_id = cur.lastrowid
    finally:
        conn.close()

    domain_dir = f"{VMAIL_BASE}/{domain}"
    os.makedirs(domain_dir, exist_ok=True)
    os.chown(domain_dir, VMAIL_UID, VMAIL_GID)
    os.chmod(domain_dir, 0o750)
    return domain_id


def delete_mail_domain(domain: str) -> None:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM mail_domain WHERE domain = %s", (domain,))  # ON DELETE CASCADE drops mail_user rows
    finally:
        conn.close()

    domain_dir = f"{VMAIL_BASE}/{domain}"
    run(["rm", "-rf", "--", domain_dir], check=False)


def _domain_id(domain: str) -> int:
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT id FROM mail_domain WHERE domain = %s", (domain,))
            row = cur.fetchone()
            if row is None:
                raise ValidationError(f"mail domain '{domain}' is not provisioned")
            return row["id"]
    finally:
        conn.close()


def create_mailbox(domain: str, local_part: str, password: str, quota_mb: int = 1024) -> dict:
    validate_domain(domain)
    validate_mailbox_local_part(local_part)
    domain_id = _domain_id(domain)
    password_hash = hash_password(password)

    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "INSERT INTO mail_user (domain_id, local_part, password, quota_mb, active) VALUES (%s, %s, %s, %s, 1)",
                (domain_id, local_part, password_hash, quota_mb),
            )
            mailbox_id = cur.lastrowid
    finally:
        conn.close()

    return {"id": mailbox_id, "domain": domain, "local_part": local_part, "email": f"{local_part}@{domain}", "quota_mb": quota_mb}


def delete_mailbox(domain: str, local_part: str) -> None:
    validate_domain(domain)
    validate_mailbox_local_part(local_part)
    domain_id = _domain_id(domain)
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM mail_user WHERE domain_id = %s AND local_part = %s", (domain_id, local_part))
    finally:
        conn.close()

    maildir = f"{VMAIL_BASE}/{domain}/{local_part}"
    run(["rm", "-rf", "--", maildir], check=False)


def list_mailboxes(domain: str) -> list[dict]:
    validate_domain(domain)
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT m.local_part, m.quota_mb, m.active FROM mail_user m "
                "JOIN mail_domain d ON m.domain_id = d.id WHERE d.domain = %s ORDER BY m.local_part",
                (domain,),
            )
            return cur.fetchall()
    finally:
        conn.close()


def change_mailbox_password(domain: str, local_part: str, new_password: str) -> None:
    validate_domain(domain)
    validate_mailbox_local_part(local_part)
    domain_id = _domain_id(domain)
    password_hash = hash_password(new_password)
    conn = _connect()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE mail_user SET password = %s WHERE domain_id = %s AND local_part = %s",
                (password_hash, domain_id, local_part),
            )
    finally:
        conn.close()
