import {
  PiArchiveDuotone, PiArrowsClockwiseDuotone, PiArrowsLeftRightDuotone,
  PiBellRingingDuotone, PiBookOpenTextDuotone, PiBrowserDuotone, PiBrowsersDuotone,
  PiBugDuotone, PiCertificateDuotone, PiChartBarDuotone, PiChartLineDuotone,
  PiClockCountdownDuotone, PiCloudArrowDownDuotone, PiCloudDuotone,
  PiCodeBlockDuotone, PiCpuDuotone, PiDatabaseDuotone, PiDesktopTowerDuotone,
  PiDownloadSimpleDuotone, PiEnvelopeDuotone, PiFileArchiveDuotone,
  PiFileCodeDuotone, PiFileMagnifyingGlassDuotone, PiFileTextDuotone,
  PiFileXDuotone, PiFireDuotone, PiFolderLockDuotone, PiFolderOpenDuotone,
  PiGaugeDuotone, PiGearSixDuotone, PiGlobeHemisphereWestDuotone,
  PiHardDrivesDuotone, PiKeyDuotone, PiLightningDuotone, PiLinkDuotone,
  PiListChecksDuotone, PiListMagnifyingGlassDuotone, PiLockKeyDuotone,
  PiMailboxDuotone, PiNetworkDuotone, PiNetworkSlashDuotone, PiPackageDuotone,
  PiPaintBrushDuotone, PiPaperPlaneTiltDuotone, PiPasswordDuotone,
  PiPipeWrenchDuotone, PiPulseDuotone, PiRocketLaunchDuotone,
  PiShareNetworkDuotone, PiShieldCheckDuotone, PiShieldPlusDuotone,
  PiShieldWarningDuotone, PiSignpostDuotone, PiSlidersHorizontalDuotone,
  PiStackDuotone, PiTerminalWindowDuotone, PiTreeStructureDuotone,
  PiUploadSimpleDuotone, PiUserGearDuotone, PiUserPlusDuotone,
  PiUsersDuotone, PiWebhooksLogoDuotone,
} from 'react-icons/pi'
import { getProductBrandIcon } from '@/components/icons/BrandIcons'

// Evo uses a consistent duotone icon vocabulary composed from Phosphor's
// MIT-licensed vectors. Product features continue to use their official marks.
const routeIcons = {
  '/domains': PiGlobeHemisphereWestDuotone,
  '/subdomains': PiBrowsersDuotone,
  '/ftp': PiUploadSimpleDuotone,
  '/ssl': PiCertificateDuotone,
  '/databases': PiDatabaseDuotone,
  '/dns': PiShareNetworkDuotone,
  '/email': PiEnvelopeDuotone,
  '/email/settings': PiSlidersHorizontalDuotone,
  '/email/dns': PiMailboxDuotone,
  '/email/spam': PiShieldCheckDuotone,
  '/email/migration': PiArrowsLeftRightDuotone,
  '/files': PiFolderOpenDuotone,
  '/php': PiFileCodeDuotone,
  '/redirects': PiSignpostDuotone,
  '/forwarding': PiLinkDuotone,
  '/cache': PiLightningDuotone,
  '/website-maintenance': PiPipeWrenchDuotone,
  '/error-pages': PiFileXDuotone,
  '/cron': PiClockCountdownDuotone,
  '/ssh': PiKeyDuotone,
  '/terminal': PiTerminalWindowDuotone,
  '/logs': PiListMagnifyingGlassDuotone,
  '/devtools': PiCodeBlockDuotone,
  '/change-password': PiPasswordDuotone,
  '/appearance': PiPaintBrushDuotone,
  '/disk-usage': PiHardDrivesDuotone,
  '/website-statistics': PiChartBarDuotone,
  '/processes': PiCpuDuotone,
  '/malware': PiBugDuotone,
  '/website-security': PiShieldWarningDuotone,
  '/security': PiLockKeyDuotone,
  '/accounts': PiUsersDuotone,
  '/resellers': PiUserGearDuotone,
  '/administrators': PiShieldCheckDuotone,
  '/plans': PiPackageDuotone,
  '/import/accounts': PiCloudArrowDownDuotone,
  '/health': PiPulseDuotone,
  '/resource-manager': PiGaugeDuotone,
  '/filesystem-isolation': PiFolderLockDuotone,
  '/security-center': PiShieldCheckDuotone,
  '/stack-manager': PiStackDuotone,
  '/services': PiGearSixDuotone,
  '/openlitespeed': PiRocketLaunchDuotone,
  '/db-monitor': PiDatabaseDuotone,
  '/slow-queries': PiChartLineDuotone,
  '/dns-setup': PiTreeStructureDuotone,
  '/cloudflare': PiCloudDuotone,
  '/dns-cluster': PiShareNetworkDuotone,
  '/ip-management': PiNetworkDuotone,
  '/updates': PiArrowsClockwiseDuotone,
  '/mail-queue': PiPaperPlaneTiltDuotone,
  '/mail-tracking': PiFileMagnifyingGlassDuotone,
  '/imap-migrations': PiArrowsLeftRightDuotone,
  '/notifications': PiBellRingingDuotone,
  '/templates': PiFileTextDuotone,
  '/maintenance-mode': PiPipeWrenchDuotone,
  '/firewall': PiFireDuotone,
  '/fail2ban': PiShieldWarningDuotone,
  '/waf': PiShieldCheckDuotone,
  '/ip-bans': PiNetworkSlashDuotone,
  '/ip-whitelist': PiShieldPlusDuotone,
  '/tokens': PiKeyDuotone,
  '/bandwidth': PiChartBarDuotone,
  '/site-stats': PiChartLineDuotone,
  '/audit-log': PiListChecksDuotone,
  '/account-log': PiFileMagnifyingGlassDuotone,
  '/error-log': PiFileXDuotone,
  '/webhooks': PiWebhooksLogoDuotone,
  '/panel-settings': PiSlidersHorizontalDuotone,
  '/server-setup': PiDesktopTowerDuotone,
  '/branding': PiPaintBrushDuotone,
  '/api/docs': PiBookOpenTextDuotone,
}

const exactIcons = {
  '/accounts?new=1': PiUserPlusDuotone,
  '/email?webmail=1': PiBrowserDuotone,
  '/backups?action=create&kind=full': PiArchiveDuotone,
  '/backups?action=create&kind=file': PiFileArchiveDuotone,
  '/backups?action=create&kind=database': PiDatabaseDuotone,
  '/backups?action=create&kind=databases': PiDatabaseDuotone,
  '/backups?action=create&kind=mailbox': PiEnvelopeDuotone,
  '/backups?view=restores': PiDownloadSimpleDuotone,
  '/backups?component=files': PiFileArchiveDuotone,
  '/backups?component=databases': PiDatabaseDuotone,
  '/backups?component=mail': PiEnvelopeDuotone,
  '/backup-jobs': PiArchiveDuotone,
  '/backup-jobs?tab=jobs': PiClockCountdownDuotone,
  '/backup-jobs?tab=jobs&action=create': PiClockCountdownDuotone,
  '/backup-jobs?tab=destinations': PiCloudDuotone,
  '/backup-jobs?tab=destinations&action=create': PiCloudDuotone,
  '/backup-jobs?tab=history': PiDownloadSimpleDuotone,
  '/backup-jobs?tab=notifications': PiBellRingingDuotone,
}

export function EvoToolIcon({ to, fallback: Fallback }) {
  const path = to?.split('?')[0]
  const Brand = getProductBrandIcon(path)
  if (Brand) return <Brand className="evo-brand-glyph" />
  const Icon = exactIcons[to] || routeIcons[path] || Fallback
  return Icon ? <Icon className="evo-duotone-icon" aria-hidden="true" /> : null
}
