import {
  FcAcceptDatabase, FcAddDatabase, FcAddressBook, FcAlarmClock, FcApproval,
  FcAreaChart, FcAutomatic, FcBarChart, FcBusinessman, FcClearFilters,
  FcComboChart, FcCommandLine, FcConferenceCall, FcCustomerSupport,
  FcDataBackup, FcDataConfiguration, FcDataEncryption, FcDataProtection,
  FcDataRecovery, FcDatabase, FcDocument, FcEngineering, FcExport, FcExternal,
  FcFeedback, FcFile, FcFlowChart, FcFolder, FcGlobe, FcImport, FcKey, FcLinux,
  FcList, FcLock, FcManager, FcMindMap, FcMultipleDevices, FcOpenedFolder,
  FcOrganization, FcOvertime, FcPackage, FcPicture, FcPieChart, FcProcess, FcRules, FcSafe,
  FcServices, FcSettings, FcStatistics, FcSynchronize, FcTemplate, FcTodoList,
  FcUpload, FcViewDetails, FcWorkflow,
} from 'react-icons/fc'
import { SiNodedotjs, SiPython } from 'react-icons/si'

const routeIcons = {
  '/domains': FcGlobe,
  '/subdomains': FcMultipleDevices,
  '/ftp': FcUpload,
  '/ssl': FcApproval,
  '/databases': FcDatabase,
  '/dns': FcMindMap,
  '/email': FcFeedback,
  '/email/settings': FcSettings,
  '/email/dns': FcOrganization,
  '/email/spam': FcClearFilters,
  '/email/migration': FcSynchronize,
  '/files': FcFolder,
  '/php': FcDataConfiguration,
  '/redirects': FcExternal,
  '/forwarding': FcExport,
  '/cache': FcAutomatic,
  '/website-maintenance': FcEngineering,
  '/error-pages': FcDocument,
  '/git': FcWorkflow,
  '/cron': FcAlarmClock,
  '/ssh': FcKey,
  '/terminal': FcCommandLine,
  '/logs': FcList,
  '/devtools': FcServices,
  '/change-password': FcDataEncryption,
  '/appearance': FcPicture,
  '/disk-usage': FcPieChart,
  '/website-statistics': FcComboChart,
  '/processes': FcProcess,
  '/malware': FcDataProtection,
  '/website-security': FcSafe,
  '/security': FcLock,
  '/accounts': FcConferenceCall,
  '/accounts/new': FcBusinessman,
  '/resellers': FcManager,
  '/administrators': FcBusinessman,
  '/plans': FcPackage,
  '/import/accounts': FcImport,
  '/health': FcStatistics,
  '/services': FcServices,
  '/openlitespeed': FcLinux,
  '/db-monitor': FcAcceptDatabase,
  '/slow-queries': FcViewDetails,
  '/cloudflare': FcGlobe,
  '/dns-cluster': FcFlowChart,
  '/ip-management': FcOrganization,
  '/updates': FcSynchronize,
  '/mail-queue': FcFeedback,
  '/mail-tracking': FcBarChart,
  '/imap-migrations': FcSynchronize,
  '/notifications': FcCustomerSupport,
  '/templates': FcTemplate,
  '/maintenance-mode': FcEngineering,
  '/firewall': FcDataProtection,
  '/fail2ban': FcRules,
  '/waf': FcSafe,
  '/ip-bans': FcLock,
  '/ip-whitelist': FcKey,
  '/tokens': FcDataEncryption,
  '/bandwidth': FcAreaChart,
  '/site-stats': FcComboChart,
  '/audit-log': FcTodoList,
  '/account-log': FcAddressBook,
  '/error-log': FcDocument,
  '/webhooks': FcWorkflow,
  '/panel-settings': FcSettings,
  '/branding': FcPicture,
  '/api/docs': FcDocument,
}

const exactIcons = {
  '/accounts?new=1': FcBusinessman,
  '/backups?action=create&kind=full': FcDataBackup,
  '/backups?action=create&kind=file': FcOpenedFolder,
  '/backups?action=create&kind=database': FcAcceptDatabase,
  '/backups?action=create&kind=databases': FcAddDatabase,
  '/backups?action=create&kind=mailbox': FcFeedback,
  '/backups?view=restores': FcDataRecovery,
  '/backups?component=files': FcOpenedFolder,
  '/backups?component=databases': FcAcceptDatabase,
  '/backups?component=mail': FcFeedback,
  '/backup-jobs': FcDataBackup,
  '/backup-jobs?tab=jobs&action=create': FcOvertime,
  '/backup-jobs?tab=destinations&action=create': FcUpload,
  '/backup-jobs?tab=history': FcDataRecovery,
  '/backup-jobs?tab=notifications': FcCustomerSupport,
}

export function EvoToolIcon({ to, fallback: Fallback }) {
  const path = to?.split('?')[0]
  if (path === '/wordpress') return <Fallback className="evo-brand-glyph" />
  if (path === '/redis') return <Fallback className="evo-brand-glyph" />
  if (path === '/node-apps' || path === '/software/node-apps') return <SiNodedotjs className="evo-brand-glyph brand-node" />
  if (path === '/python-apps' || path === '/software/python-apps') return <SiPython className="evo-brand-glyph brand-python" />
  const Icon = exactIcons[to] || routeIcons[path] || FcFile
  return <Icon className="evo-pictogram" />
}
