import {
  LayoutDashboard, Users, Globe, Mail, Database, FolderOpen, Archive, Boxes,
  Server, Network, ShieldCheck, Clock, Upload, GitBranch, KeyRound, Activity,
  Cog, Inbox, Flame, ShieldAlert, ScrollText, ShieldHalf, Gauge, ListChecks,
  Webhook, BellRing, LockKeyhole, DownloadCloud, Cpu, HardDrive, TerminalSquare, Wrench,
  History, FileCode2, Cloud, Layers, Palette, AlertOctagon, BookOpen, ArrowUpCircle,
  DatabaseZap, Construction, BarChart3, ArrowRightLeft, Ban, FileText,
} from 'lucide-react'

// Customer nav — resource pages scoped to the signed-in account. Paths are
// client-router paths (mounted under the /app basename).
export const customerNav = [
  { section: 'Overview' },
  { label: 'Dashboard', to: '/dashboard', icon: LayoutDashboard },
  { label: 'WordPress Manager', to: '/wordpress', icon: Globe },
  { section: 'Hosting' },
  { label: 'Domains', to: '/domains', icon: Globe },
  { label: 'PHP', to: '/php', icon: FileCode2 },
  { label: 'Email', to: '/email', icon: Mail },
  { label: 'Databases', to: '/databases', icon: Database },
  { label: 'Files', to: '/files', icon: FolderOpen },
  { label: 'Backups', to: '/backups', icon: Archive },
  { section: 'Apps & Services' },
  { label: 'Node.js App', to: '/node-apps', icon: Boxes },
  { label: 'Python App', to: '/python-apps', icon: FileCode2 },
  { label: 'Redis', to: '/redis', icon: Server },
  { label: 'DNS', to: '/dns', icon: Network },
  { label: 'SSL', to: '/ssl', icon: ShieldCheck },
  { label: 'Disk Usage', to: '/disk-usage', icon: HardDrive },
  { section: 'Advanced' },
  { label: 'Cron Jobs', to: '/cron', icon: Clock },
  { label: 'FTP', to: '/ftp', icon: Upload },
  { label: 'Git', to: '/git', icon: GitBranch },
  { label: 'SSH Keys', to: '/ssh', icon: KeyRound },
  { label: 'Terminal', to: '/terminal', icon: TerminalSquare },
  { label: 'Dev Tools', to: '/devtools', icon: Wrench },
  { label: 'Processes', to: '/processes', icon: Cpu },
  { label: 'Logs', to: '/logs', icon: ScrollText },
  { label: 'Security', to: '/security', icon: ShieldCheck },
  { section: 'Preferences' },
  { label: 'Appearance', to: '/appearance', icon: Palette },
  { label: 'Change Password', to: '/change-password', icon: KeyRound },
]

// Admin nav — server-wide administration + the accounts hub.
export const adminNav = [
  { section: 'Administration' },
  { label: 'Dashboard', to: '/overview', icon: LayoutDashboard },
  { label: 'WordPress Installations', to: '/wordpress', icon: Globe },
  { label: 'Accounts', to: '/accounts', icon: Users },
  { label: 'Server Health', to: '/health', icon: Activity },
  { label: 'Services', to: '/services', icon: Cog },
  // Sidebar shows an accent dot on this item while an update is available.
  { label: 'Updates', to: '/updates', icon: ArrowUpCircle },
  { section: 'Hosting Management' },
  { label: 'Backup Manager', to: '/backup-jobs', icon: Archive },
  { label: 'Plans', to: '/plans', icon: Layers },
  { label: 'Bandwidth', to: '/bandwidth', icon: Gauge },
  { label: 'Site Statistics', to: '/site-stats', icon: BarChart3 },
  { label: 'Maintenance Mode', to: '/maintenance-mode', icon: Construction },
  { section: 'Panel Configuration' },
  { label: 'Panel Settings', to: '/panel-settings', icon: Cog },
  { label: 'Branding', to: '/branding', icon: Palette },
  { label: 'Appearance', to: '/appearance', icon: Palette },
  { label: 'Change Password', to: '/change-password', icon: KeyRound },
  { label: 'Security', to: '/security', icon: ShieldCheck },
  { label: 'Templates', to: '/templates', icon: FileText },
  { section: 'Mail & Network' },
  { label: 'Mail Queue', to: '/mail-queue', icon: Inbox },
  { label: 'IMAP Migrations', to: '/imap-migrations', icon: ArrowRightLeft },
  { label: 'Firewall', to: '/firewall', icon: Flame },
  { label: 'IP Bans', to: '/ip-bans', icon: Ban },
  { label: 'Fail2ban', to: '/fail2ban', icon: ShieldAlert },
  { label: 'IP Whitelist', to: '/ip-whitelist', icon: LockKeyhole },
  { label: 'Cloudflare', to: '/cloudflare', icon: Cloud },
  { section: 'Security & Logs' },
  { label: 'Audit Log', to: '/audit-log', icon: ScrollText },
  { label: 'Account Log', to: '/account-log', icon: History },
  { label: 'Error Log', to: '/error-log', icon: AlertOctagon },
  { label: 'WAF', to: '/waf', icon: ShieldHalf },
  { label: 'Slow Queries', to: '/slow-queries', icon: ListChecks },
  { label: 'DB Monitor', to: '/db-monitor', icon: DatabaseZap },
  { label: 'API Tokens', to: '/tokens', icon: KeyRound },
  { section: 'Integrations' },
  { label: 'Webhooks', to: '/webhooks', icon: Webhook },
  { label: 'Notifications', to: '/notifications', icon: BellRing },
  { label: 'cPanel Import', to: '/import/cpanel', icon: DownloadCloud },
  // Server-rendered admin API docs (Swagger UI). external → real navigation.
  { label: 'API Docs', to: '/api/docs', icon: BookOpen, external: true },
]

export const navIcons = { Cpu, Server, DownloadCloud }
