import {
  LayoutDashboard, Users, Globe, Mail, Database, FolderOpen, Archive, Boxes,
  Server, Network, ShieldCheck, Clock, Upload, GitBranch, KeyRound, Activity,
  Cog, Inbox, Flame, ShieldAlert, ScrollText, ShieldHalf, Gauge, ListChecks,
  Webhook, BellRing, LockKeyhole, DownloadCloud, Cpu, HardDrive, TerminalSquare, Wrench,
  History, FileCode2, Cloud, Layers, Palette, AlertOctagon, BookOpen, ArrowUpCircle,
  DatabaseZap, Construction, BarChart3, ArrowRightLeft, Ban, ShieldBan, FileText, Store,
  ExternalLink, Zap, Shield, GaugeCircle, Route, ServerCog,
} from 'lucide-react'
import { WordPressIcon, RedisIcon } from '@/components/icons/BrandIcons'

// Customer nav — resource pages scoped to the signed-in account. Paths are
// client-router paths (mounted under the /app basename).
export const customerNav = [
  { section: 'Overview' },
  { label: 'Dashboard', to: '/dashboard', icon: LayoutDashboard },
  { section: 'Websites' },
  { label: 'Domains', to: '/domains', icon: Globe },
  { label: 'Subdomains', to: '/subdomains', icon: Network },
  { label: 'FTP Accounts', to: '/ftp', icon: Upload },
  { label: 'SSL Certificates', to: '/ssl', icon: ShieldCheck },
  { label: 'Databases', to: '/databases', icon: Database },
  { label: 'DNS Management', to: '/dns', icon: Network },
  { label: 'Redirects', to: '/redirects', icon: ExternalLink },
  { label: 'Domain Forwarding', to: '/forwarding', icon: ArrowRightLeft },
  { label: 'LiteSpeed Cache', to: '/cache', icon: Zap },
  { section: 'Email' },
  { label: 'Email Accounts', to: '/email', icon: Mail },
  { label: 'Webmail', to: '/email?webmail=1', icon: ExternalLink },
  { label: 'Email Settings', to: '/email/settings', icon: Cog },
  { label: 'Email DNS Records', to: '/email/dns', icon: Network },
  { label: 'Spam Filters', to: '/email/spam', icon: ShieldBan },
  { label: 'IMAP Migration', to: '/email/migration', icon: ArrowRightLeft },
  { section: 'Software' },
  { label: 'WordPress Manager', to: '/wordpress', icon: WordPressIcon },
  { label: 'Node.js App', to: '/node-apps', icon: Boxes },
  { label: 'Python App', to: '/python-apps', icon: FileCode2 },
  { label: 'Redis', to: '/redis', icon: RedisIcon },
  { section: 'Backups' },
  { label: 'Backups', to: '/backups', icon: Archive },
  { section: 'Site Tools' },
  { label: 'File Manager', to: '/files', icon: FolderOpen },
  { label: 'PHP Settings', to: '/php', icon: FileCode2 },
  { label: 'Cron Jobs', to: '/cron', icon: Clock },
  { label: 'Git', to: '/git', icon: GitBranch },
  { label: 'SSH Keys', to: '/ssh', icon: KeyRound },
  { label: 'Terminal', to: '/terminal', icon: TerminalSquare },
  { label: 'Disk Usage', to: '/disk-usage', icon: HardDrive },
  { label: 'Logs', to: '/logs', icon: ScrollText },
  { label: 'Dev Tools', to: '/devtools', icon: Wrench },
  { label: 'Change Password', to: '/change-password', icon: KeyRound },
  { label: 'Malware Scanner', to: '/malware', icon: ShieldAlert },
  { label: '2FA & Security', to: '/security', icon: ShieldCheck },
  { label: 'Processes', to: '/processes', icon: Cpu },
  { label: 'Website Security', to: '/website-security', icon: Shield },
  { label: 'Website Maintenance', to: '/website-maintenance', icon: Construction },
  { label: 'Custom Error Pages', to: '/error-pages', icon: FileText },
  { label: 'Website Statistics', to: '/website-statistics', icon: GaugeCircle },
  { label: 'Appearance', to: '/appearance', icon: Palette },
]

// Admin nav — server-wide administration + the accounts hub.
export const adminNav = [
  { section: 'Administration' },
  { label: 'Dashboard', to: '/overview', icon: LayoutDashboard },
  { label: 'WordPress Installations', to: '/wordpress', icon: WordPressIcon },
  { label: 'Accounts', to: '/accounts', icon: Users },
  { label: 'Add New User', to: '/accounts?new=1', icon: Users },
  { label: 'Resellers', to: '/resellers', icon: Store },
  { label: 'Administrators', to: '/administrators', icon: ShieldCheck },
  { label: 'Server Health', to: '/health', icon: Activity },
  { label: 'Services', to: '/services', icon: Cog },
  { label: 'OpenLiteSpeed', to: '/openlitespeed', icon: Server },
  // Sidebar shows an accent dot on this item while an update is available.
  { label: 'Updates', to: '/updates', icon: ArrowUpCircle },
  { section: 'Hosting Management' },
  { label: 'Backup Manager', to: '/backup-jobs', icon: Archive },
  { label: 'Plans', to: '/plans', icon: Layers },
  { label: 'SSL Certificates', to: '/ssl', icon: ShieldCheck },
  { label: 'Bandwidth', to: '/bandwidth', icon: Gauge },
  { label: 'Site Statistics', to: '/site-stats', icon: BarChart3 },
  { label: 'Maintenance Mode', to: '/maintenance-mode', icon: Construction },
  { label: 'Node.js Applications', to: '/software/node-apps', icon: Boxes },
  { label: 'Python Applications', to: '/software/python-apps', icon: FileCode2 },
  { section: 'Panel Configuration' },
  { label: 'Server Setup', to: '/server-setup', icon: ServerCog },
  { label: 'Panel Settings', to: '/panel-settings', icon: Cog },
  { label: 'Branding', to: '/branding', icon: Palette },
  { label: 'Appearance', to: '/appearance', icon: Palette },
  { label: 'Security', to: '/security', icon: ShieldCheck },
  { label: 'Templates', to: '/templates', icon: FileText },
  { section: 'Mail & Network' },
  { label: 'Mail Queue', to: '/mail-queue', icon: Inbox },
  { label: 'Email Tracking', to: '/mail-tracking', icon: BarChart3 },
  { label: 'IMAP Migrations', to: '/imap-migrations', icon: ArrowRightLeft },
  { label: 'Firewall', to: '/firewall', icon: Flame },
  { label: 'IP Management', to: '/ip-management', icon: Network },
  { label: 'IP Bans', to: '/ip-bans', icon: Ban },
  { label: 'Fail2ban', to: '/fail2ban', icon: ShieldAlert },
  { label: 'IP Whitelist', to: '/ip-whitelist', icon: LockKeyhole },
  { label: 'DNS Setup', to: '/dns-setup', icon: Route },
  { label: 'Cloudflare', to: '/cloudflare', icon: Cloud },
  { label: 'DNS Cluster', to: '/dns-cluster', icon: Network },
  { section: 'Security & Logs' },
  { label: 'Malware Scanner', to: '/malware', icon: ShieldAlert },
  { label: 'Audit Log', to: '/audit-log', icon: ScrollText },
  { label: 'Account Log', to: '/account-log', icon: History },
  { label: 'Error Log', to: '/error-log', icon: AlertOctagon },
  { label: 'WAF', to: '/waf', icon: ShieldHalf },
  { label: 'Slow Queries', to: '/slow-queries', icon: ListChecks },
  { label: 'DB Monitor', to: '/db-monitor', icon: DatabaseZap },
  { label: 'API Tokens', to: '/tokens', icon: KeyRound },
  { section: 'Integrations' },
  { label: 'Webhooks', to: '/webhooks', icon: Webhook },
  { label: 'Notifications', to: '/notifications', icon: BellRing },
  { label: 'Account Migrations', to: '/import/accounts', icon: DownloadCloud },
  // Server-rendered admin API docs (Swagger UI). external → real navigation.
  { label: 'API Docs', to: '/api/docs', icon: BookOpen, external: true },
]

export const resellerNav = [
  { section: 'Reseller' },
  { label: 'Accounts Overview', to: '/reseller', icon: LayoutDashboard },
  { section: 'Preferences' },
  { label: 'Change Password', to: '/change-password', icon: KeyRound },
  { label: '2FA & Security', to: '/security', icon: ShieldCheck },
  { label: 'Appearance', to: '/appearance', icon: Palette },
]

export const navIcons = { Cpu, Server, DownloadCloud }
