// Read-only smoke test of a deployed Boron panel. Credentials stay outside Git.
import { chromium } from 'playwright'
import { expect } from '@playwright/test'
import fs from 'node:fs'
const creds = JSON.parse(fs.readFileSync(process.env.BORON_CREDENTIALS_FILE, 'utf8'))
const base = process.env.BORON_TEST_URL || 'https://127.0.0.1:9443'
const output = process.env.BORON_SCREENSHOT_DIR || '/tmp/boron-theme-screenshots'
fs.mkdirSync(output, { recursive: true })
const browser = await chromium.launch({ headless: true })
const context = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 1000 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
const missingAssets = []
page.on('response', (r) => { if (r.url().includes('/static/dist/') && r.status() >= 400) missingAssets.push(r.url()) })
try {
  await page.goto(`${base}/app/login`)
  await page.getByLabel('Username', { exact: true }).fill(creds.username)
  await page.locator('input#password').fill(creds.password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/app\/overview$/, { timeout: 30000 })
  await expect(page.getByRole('heading', { name: 'Admin Dashboard' })).toBeVisible()
  for (const [skin, name] of [['evolution', 'Evo'], ['paper-lantern', 'Paper']]) {
    await page.getByRole('button', { name: 'Choose theme', exact: true }).first().click()
    await page.getByRole('menuitemradio', { name: new RegExp(name) }).click()
    await expect(page.locator('html')).toHaveAttribute('data-skin', skin)
    await expect(page.getByRole('progressbar', { name: 'CPU Usage' })).toBeVisible()
    await expect(page.locator('.query-notice')).toHaveCount(0)
    await page.screenshot({ path: `${output}/${skin}-desktop.png` })
    await page.locator('.tool-link').filter({ hasText: 'Manage Accounts' }).click()
    await expect(page.getByRole('heading', { name: 'Accounts', exact: true })).toBeVisible()
    await page.screenshot({ path: `${output}/${skin}-accounts.png` })
    await page.goto(`${base}/app/change-password`)
    await expect(page.getByRole('heading', { name: 'Change password' })).toBeVisible()
    await page.locator('input[type=password]').first().fill('unsaved-verification-only')
    await page.getByRole('button', { name: 'Switch to dark mode', exact: true }).click()
    await expect(page.locator('input[type=password]').first()).toHaveValue('unsaved-verification-only')
    await page.screenshot({ path: `${output}/${skin}-form-dark.png` })
    await page.getByRole('button', { name: 'Switch to light mode', exact: true }).click()
    await page.goto(`${base}/app/appearance`)
    await expect(page.getByRole('button', { name: `Use ${name} theme` })).toHaveAttribute('aria-pressed', 'true')
    await page.screenshot({ path: `${output}/${skin}-appearance.png` })
    await page.reload()
    await expect(page.locator('html')).toHaveAttribute('data-skin', skin)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto(`${base}/app/overview`)
    await expect(page.locator('.tool-link').first()).toBeVisible()
    await page.screenshot({ path: `${output}/${skin}-mobile.png` })
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
    expect(overflow).toBe(false)
    await page.setViewportSize({ width: 1440, height: 1000 })
    console.log(`${name}: real login, live statistics, accounts, form, appearance, persistence and mobile passed`)
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`${base}/app/plans/new`)
  await expect(page.getByRole('heading', { name: 'Create Hosting Plan' })).toBeVisible()
  await expect(page.getByText('Compute resources', { exact: true })).toBeVisible()
  await page.screenshot({ path: `${output}/paper-plan-editor.png`, fullPage: true })
  await page.goto(`${base}/app/openlitespeed`)
  await expect(page.getByRole('heading', { name: 'OpenLiteSpeed' })).toBeVisible()
  await expect(page.getByText('Trusted certificate', { exact: true })).toBeVisible()
  await page.screenshot({ path: `${output}/paper-openlitespeed.png`, fullPage: true })

  const accountsResponse = await context.request.get(`${base}/api/v1/accounts`)
  expect(accountsResponse.status()).toBe(200)
  const accountsPayload = await accountsResponse.json()
  const accounts = Array.isArray(accountsPayload) ? accountsPayload : accountsPayload.accounts
  const reviewAccount = accounts?.find((item) => item.status === 'active')
  expect(reviewAccount?.username).toBeTruthy()
  const impersonation = await context.request.post(`${base}/api/v1/admin/accounts/${reviewAccount.username}/impersonate`)
  expect(impersonation.status()).toBe(200)
  const { token } = await impersonation.json()
  const redeemed = await context.request.post(`${base}/api/v1/impersonate/redeem`, { data: { token } })
  expect(redeemed.status()).toBe(200)
  try {
    await page.goto(`${base}/app/dashboard`)
    await expect(page.getByRole('heading', { name: 'Hosting Dashboard' })).toBeVisible()
    await expect(page.getByText('Email Accounts', { exact: true }).first()).toBeVisible()
    await page.screenshot({ path: `${output}/paper-customer-dashboard.png`, fullPage: true })
    await page.goto(`${base}/app/subdomains`)
    await page.getByRole('button', { name: 'Add subdomain', exact: true }).first().click()
    await expect(page.getByLabel('Parent domain', { exact: true })).toBeVisible()
    await expect(page.getByLabel('Document root', { exact: true })).toBeVisible()
    await page.screenshot({ path: `${output}/paper-subdomain-form.png`, fullPage: true })
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.goto(`${base}/app/backups`)
    await page.getByRole('button', { name: 'Create backup', exact: true }).first().click()
    await page.getByLabel('What to back up').selectOption('database')
    await expect(page.getByLabel('Database')).toBeVisible()
    await page.screenshot({ path: `${output}/paper-database-backup.png`, fullPage: true })
    await page.getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.goto(`${base}/app/php`)
    await expect(page.getByRole('heading', { name: 'PHP', exact: true })).toBeVisible()
    await page.screenshot({ path: `${output}/paper-php.png`, fullPage: true })
  } finally {
    const returned = await context.request.post(`${base}/api/v1/impersonate/return`)
    expect(returned.status()).toBe(200)
  }
  // API-only impersonation changes the cookie without updating the SPA's
  // cached identity. The first navigation lets AppShell reconcile that cache;
  // navigate again once the restored admin controls are visible.
  await page.goto(`${base}/app/overview`)
  await expect(page.getByRole('button', { name: 'Select account' })).toBeVisible({ timeout: 30000 })
  await page.goto(`${base}/app/overview`)
  await expect(page.getByRole('heading', { name: 'Admin Dashboard' })).toBeVisible({ timeout: 30000 })
  console.log('Full-page plans, OLS TLS, customer metrics, subdomain, database backup and PHP screens passed.')
  if (process.env.BORON_EXPECTED_VERSION) {
    const response = await context.request.get(`${base}/api/v1/admin/update/status`)
    expect(response.status()).toBe(200)
    const status = await response.json()
    expect(status.current_version).toBe(process.env.BORON_EXPECTED_VERSION)
    expect(status.active_job).toBeNull()
    expect(status.last_job.status).toBe('completed')
    expect(status.rollback_available).toBe(true)
    const history = await context.request.get(`${base}/api/v1/admin/update/history`)
    expect(history.status()).toBe(200)
    await page.goto(`${base}/app/updates`)
    await expect(page.getByRole('heading', { name: 'Updates', exact: true })).toBeVisible()
    await expect(page.getByText('v' + process.env.BORON_EXPECTED_VERSION, { exact: true }).first()).toBeVisible()
    await page.screenshot({ path: `${output}/updates-completed.png` })
    console.log('Updates page, version, completed job, history and rollback availability passed.')
  }
  expect(errors).toEqual([])
  expect(missingAssets).toEqual([])
  console.log('No uncaught browser errors or failed static assets.')
} finally { await browser.close() }
