import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Cpu, Database, Gauge, Layers, Mail, Save, Server } from 'lucide-react'
import { get, patch, post } from '@/lib/api'
import { PLAN_PRESETS } from './Plans'
import { PageHeader } from '@/components/ui/PageHeader'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input, FormField } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Switch } from '@/components/ui/Toggle'
import { CenteredSpinner } from '@/components/ui/Spinner'
import { ErrorState } from '@/components/ui/States'
import { toast } from '@/components/ui/Toast'

const CPU_PRESETS = ['0.25', '0.5', '1', '2', '4', '8']
const EMPTY = { name: '', cpu_cores: .5, cpu_weight: 100, memory_high_gb: .875, memory_max_gb: 1, io_read_mb: 50, io_write_mb: 50, io_read_iops: 500, io_write_iops: 250, nproc: 100, entry_processes: 20, mem_mb: 1024, io_mb: 50, pids_max: 100, quota_soft_gb: 10, quota_hard_gb: 12, bandwidth_limit_gb: '', database_limit: '', email_account_limit: '', subdomain_limit: '', ftp_account_limit: '', app_limit: '', redis_enabled: true }
const optional = ['database_limit', 'email_account_limit', 'subdomain_limit', 'ftp_account_limit', 'app_limit']
function NumberField({ form, setForm, name, label, min = 1, step = 1, placeholder, hint }) { return <FormField label={label} hint={hint}><Input type="number" min={min} step={step} placeholder={placeholder} value={form[name]} onChange={event => setForm(value => ({ ...value, [name]: event.target.value }))} /></FormField> }
function Section({ icon: Icon, title, description, children }) { return <Card className="plan-editor-section"><CardHeader><div><CardTitle className="flex items-center gap-2"><Icon className="h-5 w-5" />{title}</CardTitle><CardDescription>{description}</CardDescription></div></CardHeader><CardContent><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{children}</div></CardContent></Card> }
function fromPlan(plan) { const result = { ...EMPTY, ...plan, cpu_cores: plan.cpu_cores ?? plan.cpu_pct / 100, memory_high_gb: (plan.memory_high_mb ?? Math.round((plan.mem_mb || 1024) * .9)) / 1024, memory_max_gb: (plan.memory_max_mb ?? plan.mem_mb) / 1024, quota_soft_gb: plan.quota_soft_mb / 1024, quota_hard_gb: plan.quota_hard_mb / 1024, bandwidth_limit_gb: plan.bandwidth_limit_mb == null ? '' : plan.bandwidth_limit_mb / 1024, io_read_mb: plan.io_read_bps == null ? '' : Math.round(plan.io_read_bps / 1048576), io_write_mb: plan.io_write_bps == null ? '' : Math.round(plan.io_write_bps / 1048576), io_read_iops: plan.io_read_iops ?? 500, io_write_iops: plan.io_write_iops ?? 250, nproc: plan.nproc ?? plan.pids_max }; optional.forEach(key => { result[key] = plan[key] ?? '' }); return result }
function payload(form) { const cpu = form.cpu_cores === '' ? null : Number(form.cpu_cores); const memoryMax = form.memory_max_gb === '' ? null : Math.round(Number(form.memory_max_gb) * 1024); const readMb = form.io_read_mb === '' ? null : Number(form.io_read_mb); const writeMb = form.io_write_mb === '' ? null : Number(form.io_write_mb); const nproc = form.nproc === '' ? null : Number(form.nproc); const body = { name: form.name.trim(), cpu_pct: cpu == null ? 25 : Math.round(cpu * 100), cpu_cores: cpu, cpu_weight: form.cpu_weight === '' ? null : Number(form.cpu_weight), mem_mb: memoryMax ?? 1024, memory_high_mb: form.memory_high_gb === '' ? null : Math.round(Number(form.memory_high_gb) * 1024), memory_max_mb: memoryMax, io_mb: readMb ?? writeMb ?? 50, io_read_bps: readMb == null ? null : readMb * 1048576, io_write_bps: writeMb == null ? null : writeMb * 1048576, io_read_iops: form.io_read_iops === '' ? null : Number(form.io_read_iops), io_write_iops: form.io_write_iops === '' ? null : Number(form.io_write_iops), pids_max: nproc ?? 100, nproc, entry_processes: form.entry_processes === '' ? null : Number(form.entry_processes), quota_soft_mb: Math.round(Number(form.quota_soft_gb) * 1024), quota_hard_mb: Math.round(Number(form.quota_hard_gb) * 1024), bandwidth_limit_mb: form.bandwidth_limit_gb === '' ? null : Math.round(Number(form.bandwidth_limit_gb) * 1024), redis_enabled: !!form.redis_enabled }; optional.forEach(key => { body[key] = form[key] === '' ? null : Number(form[key]) }); return body }

export default function PlanEditor() {
  const { planId } = useParams(); const editing = !!planId; const navigate = useNavigate(); const qc = useQueryClient()
  const [form, setForm] = useState({ ...EMPTY }); const [template, setTemplate] = useState('wordpress')
  const [cpuMode, setCpuMode] = useState('0.5')
  const capacityQuery = useQuery({ queryKey: ['resource-manager'], queryFn: () => get('/api/v1/admin/resources'), staleTime: 30000 })
  const cpuCapacity = capacityQuery.data?.host?.cpu_cores
  const query = useQuery({ queryKey: ['plan', planId], queryFn: () => get(`/api/v1/admin/plans/${planId}`), enabled: editing })
  useEffect(() => { const next = query.data ? fromPlan(query.data) : !editing ? fromPlan(PLAN_PRESETS.wordpress.values) : null; if (next) { setForm(next); const value = next.cpu_cores === '' || next.cpu_cores == null ? 'unlimited' : String(next.cpu_cores); setCpuMode(CPU_PRESETS.includes(value) ? value : 'custom') } }, [query.data, editing])
  const save = useMutation({ mutationFn: body => editing ? patch(`/api/v1/admin/plans/${planId}`, body) : post('/api/v1/admin/plans', body), onSuccess: () => { toast.success(editing ? 'Plan updated' : 'Plan created'); qc.invalidateQueries({ queryKey: ['plans'] }); navigate('/plans') }, onError: error => toast.error('Could not save plan', error.message) })
  if (editing && query.isLoading) return <CenteredSpinner />
  if (editing && query.error) return <ErrorState error={query.error} onRetry={query.refetch} />
  return <form className="plan-editor" onSubmit={event => { event.preventDefault(); save.mutate(payload(form)) }}>
    <PageHeader title={editing ? `Edit ${query.data?.name || 'plan'}` : 'Create Hosting Plan'} description="Set account resources and service limits in clearly separated sections." icon={Layers}><Button asChild variant="secondary"><Link to="/plans"><ArrowLeft className="h-4 w-4" /> Plans</Link></Button><Button type="submit" loading={save.isPending} disabled={!form.name.trim()}><Save className="h-4 w-4" /> Save plan</Button></PageHeader>
    {!editing && <Section icon={Layers} title="Plan template" description="Start with sensible values, then adjust any limit."><FormField label="Starting template"><Select value={template} onChange={event => { const id = event.target.value; setTemplate(id); if (PLAN_PRESETS[id]) setForm(fromPlan(PLAN_PRESETS[id].values)) }}>{Object.entries(PLAN_PRESETS).map(([id, item]) => <option key={id} value={id}>{item.label} — {item.description}</option>)}</Select></FormField><FormField label="Plan name"><Input autoFocus required value={form.name} onChange={event => setForm(value => ({ ...value, name: event.target.value }))} /></FormField></Section>}
    {editing && <Section icon={Layers} title="Plan identity" description="The name administrators see when assigning this package."><FormField label="Plan name"><Input autoFocus required value={form.name} onChange={event => setForm(value => ({ ...value, name: event.target.value }))} /></FormField></Section>}
    <Section icon={Cpu} title="Compute resources" description={`Sustained work is throttled at the CPU allocation; this server currently exposes ${cpuCapacity ?? '…'} logical cores.`}><FormField label="CPU allocation"><Select value={cpuMode} onChange={event => { const value = event.target.value; setCpuMode(value); if (value === 'unlimited') setForm(current => ({ ...current, cpu_cores: '' })); else if (value !== 'custom') setForm(current => ({ ...current, cpu_cores: value })) }}>{CPU_PRESETS.filter(value => !cpuCapacity || Number(value) <= cpuCapacity).map(value => <option key={value} value={value}>{value === '0.25' ? '¼' : value === '0.5' ? '½' : value} {Number(value) === 1 ? 'core' : 'cores'}</option>)}<option value="unlimited">All available CPU</option><option value="custom">Custom</option></Select></FormField>{cpuMode === 'custom' && <NumberField form={form} setForm={setForm} name="cpu_cores" label="Custom CPU cores" min={.25} step={.25} hint={cpuCapacity ? `Maximum ${cpuCapacity} cores on this server.` : undefined} />}<NumberField form={form} setForm={setForm} name="cpu_weight" label="CPU priority weight" min={1} hint="100 is the normal relative priority." /><NumberField form={form} setForm={setForm} name="nproc" label="Processes / threads (NPROC)" min={10} placeholder="Unlimited" /></Section>
    <Section icon={Gauge} title="Memory and web concurrency" description="The soft limit starts reclaiming and throttling memory before the hard limit can stop a worker."><NumberField form={form} setForm={setForm} name="memory_high_gb" label="Soft memory limit (GB)" min={.0625} step={.0625} placeholder="Unlimited" hint="Crossing this level creates memory pressure; the account can continue up to the hard limit." /><NumberField form={form} setForm={setForm} name="memory_max_gb" label="Hard memory limit (GB)" min={.0625} step={.0625} placeholder="Unlimited" /><NumberField form={form} setForm={setForm} name="entry_processes" label="Entry processes" min={1} placeholder="Unlimited" /></Section>
    <Section icon={Gauge} title="Disk, I/O and traffic" description="Storage and monthly transfer use GB; throughput remains MB/s and operation rate uses IOPS."><NumberField form={form} setForm={setForm} name="quota_soft_gb" label="Disk soft quota (GB)" step={.25} /><NumberField form={form} setForm={setForm} name="quota_hard_gb" label="Disk hard quota (GB)" step={.25} /><NumberField form={form} setForm={setForm} name="io_read_mb" label="Read throughput (MB/s)" placeholder="Unlimited" /><NumberField form={form} setForm={setForm} name="io_write_mb" label="Write throughput (MB/s)" placeholder="Unlimited" /><NumberField form={form} setForm={setForm} name="io_read_iops" label="Read IOPS" /><NumberField form={form} setForm={setForm} name="io_write_iops" label="Write IOPS" /><NumberField form={form} setForm={setForm} name="bandwidth_limit_gb" label="Monthly bandwidth (GB)" placeholder="Unlimited" hint="Blank means unlimited." /></Section>
    <Section icon={Server} title="Websites and applications" description="How many hosted resources an account may create."><NumberField form={form} setForm={setForm} name="subdomain_limit" label="Subdomains" placeholder="Unlimited" /><NumberField form={form} setForm={setForm} name="ftp_account_limit" label="FTP accounts" placeholder="Unlimited" /><NumberField form={form} setForm={setForm} name="app_limit" label="Node.js / Python apps" placeholder="Unlimited" /></Section>
    <Section icon={Mail} title="Email" description="Mailbox allowance for domains owned by the account."><NumberField form={form} setForm={setForm} name="email_account_limit" label="Email accounts" placeholder="Unlimited" /></Section>
    <Section icon={Database} title="Databases and software" description="Database allowance and managed software defaults."><NumberField form={form} setForm={setForm} name="database_limit" label="Databases" placeholder="Unlimited" /><label className="plan-switch"><span><strong>Redis</strong><small>Provision an isolated Redis instance when this plan is applied.</small></span><Switch checked={form.redis_enabled} onCheckedChange={checked => setForm(value => ({ ...value, redis_enabled: checked }))} /></label></Section>
    <div className="plan-editor-actions"><Button asChild variant="secondary"><Link to="/plans">Cancel</Link></Button><Button type="submit" loading={save.isPending} disabled={!form.name.trim()}><Save className="h-4 w-4" /> Save plan</Button></div>
  </form>
}
